theme: jekyll-theme-minimal
url: "rlc26.github.io"
title: "Danse Latine"
description: "Description des danses latines SBK"
dance_styles:
  - name: "Salsa"
    description: "Danse rythmée d'origine cubaine, influencée par le jazz et la musique latine, avec des mouvements rapides et une forte connexion au rythme."
    origin: "Cuba"
  - name: "Bachata"
    description: "Danse originaire de la République dominicaine, reconnue pour ses pas de base simples et son style romantique."
    origin: "République dominicaine"
  - name: "Kizomba"
    description: "Danse sensuelle et fluide originaire d'Angola, caractérisée par une connexion proche et des mouvements doux."
    origin: "Angola"

